name: CI

on:
  pull_request:
  merge_group:
  schedule:
    - cron: '42 2 * * SAT' # At 2:42 UTC every Saturday.

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable

      - name: Build
        run: RUSTFLAGS="-D warnings" cargo build --locked
