name: CI

on:
  push:
    branches:
    - 'master'
  pull_request:
    branches:
    - 'master'
  merge_group:
  schedule:
    - cron: '2 42 * * SAT' # At 2:42 UTC every Saturday.

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install correct toolchain
        shell: bash
        run: |
          if [[ ${{ github.event_name }} == 'schedule' ]]; then
            RUST_TOOLCHAIN=nightly
          else
            RUST_TOOLCHAIN=$(cat rust-version)
          fi
          echo "Installing Rust version: $RUST_TOOLCHAIN"
          rustup override set $RUST_TOOLCHAIN

      - name: Show Rust version
        run: |
          rustup show
          rustc -Vv
          cargo -V

      - name: Build
        run: RUSTFLAGS="-D warnings" cargo build --locked
